/*
 * Warning, this header file is automatically generated
 */

#define NUM_FISH	29

#include "fishmaps/QueenAngel.h"
#include "fishmaps/blueking.h"
#include "fishmaps/blueking2.h"
#include "fishmaps/butfish.h"
#include "fishmaps/cichlid1.h"
#include "fishmaps/cichlid4.h"
#include "fishmaps/collaris.h"
#include "fishmaps/discus2.h"
#include "fishmaps/discus3.h"
#include "fishmaps/eel.h"
#include "fishmaps/f00.h"
#include "fishmaps/f01.h"
#include "fishmaps/f02.h"
#include "fishmaps/f03.h"
#include "fishmaps/f04.h"
#include "fishmaps/f05.h"
#include "fishmaps/f06.h"
#include "fishmaps/f07.h"
#include "fishmaps/f08.h"
#include "fishmaps/f09.h"
#include "fishmaps/f10.h"
#include "fishmaps/f11.h"
#include "fishmaps/f12.h"
#include "fishmaps/f13.h"
#include "fishmaps/manta.h"
#include "fishmaps/newf1.h"
#include "fishmaps/shark1.h"
#include "fishmaps/six_barred.h"
#include "fishmaps/teeth.h"

int rwidth[] = {
	QueenAngel_width,
	blueking_width,
	blueking2_width,
	butfish_width,
	cichlid1_width,
	cichlid4_width,
	collaris_width,
	discus2_width,
	discus3_width,
	eel_width,
	f00_width,
	f01_width,
	f02_width,
	f03_width,
	f04_width,
	f05_width,
	f06_width,
	f07_width,
	f08_width,
	f09_width,
	f10_width,
	f11_width,
	f12_width,
	f13_width,
	manta_width,
	newf1_width,
	shark1_width,
	six_barred_width,
	teeth_width,
};

int rheight[] = {
	QueenAngel_height,
	blueking_height,
	blueking2_height,
	butfish_height,
	cichlid1_height,
	cichlid4_height,
	collaris_height,
	discus2_height,
	discus3_height,
	eel_height,
	f00_height,
	f01_height,
	f02_height,
	f03_height,
	f04_height,
	f05_height,
	f06_height,
	f07_height,
	f08_height,
	f09_height,
	f10_height,
	f11_height,
	f12_height,
	f13_height,
	manta_height,
	newf1_height,
	shark1_height,
	six_barred_height,
	teeth_height,
};

int rcolors[] = {
	QueenAngel_colors,
	blueking_colors,
	blueking2_colors,
	butfish_colors,
	cichlid1_colors,
	cichlid4_colors,
	collaris_colors,
	discus2_colors,
	discus3_colors,
	eel_colors,
	f00_colors,
	f01_colors,
	f02_colors,
	f03_colors,
	f04_colors,
	f05_colors,
	f06_colors,
	f07_colors,
	f08_colors,
	f09_colors,
	f10_colors,
	f11_colors,
	f12_colors,
	f13_colors,
	manta_colors,
	newf1_colors,
	shark1_colors,
	six_barred_colors,
	teeth_colors,
};

int rback[] = {
	QueenAngel_back,
	blueking_back,
	blueking2_back,
	butfish_back,
	cichlid1_back,
	cichlid4_back,
	collaris_back,
	discus2_back,
	discus3_back,
	eel_back,
	f00_back,
	f01_back,
	f02_back,
	f03_back,
	f04_back,
	f05_back,
	f06_back,
	f07_back,
	f08_back,
	f09_back,
	f10_back,
	f11_back,
	f12_back,
	f13_back,
	manta_back,
	newf1_back,
	shark1_back,
	six_barred_back,
	teeth_back,
};

int *rreds[] = {
	QueenAngel_reds,
	blueking_reds,
	blueking2_reds,
	butfish_reds,
	cichlid1_reds,
	cichlid4_reds,
	collaris_reds,
	discus2_reds,
	discus3_reds,
	eel_reds,
	f00_reds,
	f01_reds,
	f02_reds,
	f03_reds,
	f04_reds,
	f05_reds,
	f06_reds,
	f07_reds,
	f08_reds,
	f09_reds,
	f10_reds,
	f11_reds,
	f12_reds,
	f13_reds,
	manta_reds,
	newf1_reds,
	shark1_reds,
	six_barred_reds,
	teeth_reds,
};

int *rgreens[] = {
	QueenAngel_greens,
	blueking_greens,
	blueking2_greens,
	butfish_greens,
	cichlid1_greens,
	cichlid4_greens,
	collaris_greens,
	discus2_greens,
	discus3_greens,
	eel_greens,
	f00_greens,
	f01_greens,
	f02_greens,
	f03_greens,
	f04_greens,
	f05_greens,
	f06_greens,
	f07_greens,
	f08_greens,
	f09_greens,
	f10_greens,
	f11_greens,
	f12_greens,
	f13_greens,
	manta_greens,
	newf1_greens,
	shark1_greens,
	six_barred_greens,
	teeth_greens,
};

int *rblues[] = {
	QueenAngel_blues,
	blueking_blues,
	blueking2_blues,
	butfish_blues,
	cichlid1_blues,
	cichlid4_blues,
	collaris_blues,
	discus2_blues,
	discus3_blues,
	eel_blues,
	f00_blues,
	f01_blues,
	f02_blues,
	f03_blues,
	f04_blues,
	f05_blues,
	f06_blues,
	f07_blues,
	f08_blues,
	f09_blues,
	f10_blues,
	f11_blues,
	f12_blues,
	f13_blues,
	manta_blues,
	newf1_blues,
	shark1_blues,
	six_barred_blues,
	teeth_blues,
};

unsigned char *xfishRasterA[] = {
	QueenAngel_rasterA,
	blueking_rasterA,
	blueking2_rasterA,
	butfish_rasterA,
	cichlid1_rasterA,
	cichlid4_rasterA,
	collaris_rasterA,
	discus2_rasterA,
	discus3_rasterA,
	eel_rasterA,
	f00_rasterA,
	f01_rasterA,
	f02_rasterA,
	f03_rasterA,
	f04_rasterA,
	f05_rasterA,
	f06_rasterA,
	f07_rasterA,
	f08_rasterA,
	f09_rasterA,
	f10_rasterA,
	f11_rasterA,
	f12_rasterA,
	f13_rasterA,
	manta_rasterA,
	newf1_rasterA,
	shark1_rasterA,
	six_barred_rasterA,
	teeth_rasterA,
};

unsigned char *xfishRasterB[] = {
	QueenAngel_rasterB,
	blueking_rasterB,
	blueking2_rasterB,
	butfish_rasterB,
	cichlid1_rasterB,
	cichlid4_rasterB,
	collaris_rasterB,
	discus2_rasterB,
	discus3_rasterB,
	eel_rasterB,
	f00_rasterB,
	f01_rasterB,
	f02_rasterB,
	f03_rasterB,
	f04_rasterB,
	f05_rasterB,
	f06_rasterB,
	f07_rasterB,
	f08_rasterB,
	f09_rasterB,
	f10_rasterB,
	f11_rasterB,
	f12_rasterB,
	f13_rasterB,
	manta_rasterB,
	newf1_rasterB,
	shark1_rasterB,
	six_barred_rasterB,
	teeth_rasterB,
};
